### ISSUE TITLE
week1:回顾预备知识，配置好EIDE工具链

### ISSUE THREAD

**Issue by Liber1917** [Liber1917/Embedded_training_IEST#1]

**Comment by Liber1917** [comment]
清明节240406前提交一张能表明烧录成功的截图
注意养成**留痕**的良好习惯：
- 能证明是本人
- 能证明烧录成功
- 有具体时间地点
- 如有必要，保留视频证据

**Comment by Liber1917** [comment]
tips: 在协作中，信息交流与及时反馈不仅是对集体有益的，而且通过分清权责也促成了对劳动主体的保护

此外，在非正常劳动时间，你有拒绝回应和劳动的权利！！

**Comment by kinokomoguu** [comment]
2024.4.2 21:23 科学馆
![微信图片_20240402212816](https://github.com/Liber1917/Embedded_training_IEST/assets/164481348/a730698a-efd3-4e8d-98d2-6d63003a2993)
![微信图片_20240402212343](https://github.com/Liber1917/Embedded_training_IEST/assets/164481348/63efdaa9-d736-4cc3-89ad-368ef15d75ad)

**Comment by wodecuo** [comment]
![image](https://github.com/Liber1917/Embedded_training_IEST/assets/150349730/09946219-a95d-4ab3-ae3e-d71b1edc5679)
![微信图片_20240404162541](https://github.com/Liber1917/Embedded_training_IEST/assets/150349730/e2767dd3-d4c3-4835-8c90-957e6d64099e)
![Uploading 微信图片_20240404162623.png…]()

**Comment by NEUJayson** [comment]
![648492970539655543](https://github.com/Liber1917/Embedded_training_IEST/assets/164654503/c45463c6-60fd-4c8f-9ea5-c155fda11d32)

**Comment by szdxfcgh** [comment]
![Uploading 微信图片_20240404233756.jpg…]()

**Comment by szdxfcgh** [comment]
![微信图片_20240404233756](https://github.com/Liber1917/Embedded_training_IEST/assets/164708987/4144dfd7-ff1c-4ae0-aee1-5bacf1c4bfa8)

**Comment by Liber1917** [comment]
> ![648492970539655543](https://github.com/Liber1917/Embedded_training_IEST/assets/164654503/c45463c6-60fd-4c8f-9ea5-c155fda11d32)
> 

配置EIDE工具链，我们尽量减少对keil的依赖

**Comment by Liber1917** [comment]
@NEUJayson 别用Keil了，我们得学习配置EIDE，以后的项目只会保留一个Keil的入口，不一定保证能用

**Comment by Liber1917** [comment]
@szdxfcgh 你的主函数里写的啥

**Comment by DYCfromNEU** [comment]
![Uploading 微信图片_20240405141836.jpg…]()

**Comment by YouNeo1984** [comment]
![IMG_20240405_150941.jpg](https://github.com/Liber1917/Embedded_training_IEST/assets/164765259/15345728-3b4c-4219-9a92-d79e69a20761)

2024.4.5

**Comment by NEUJayson** [comment]
![505649605242969061](https://github.com/Liber1917/Embedded_training_IEST/assets/164654503/28da90c9-a3b8-4cb0-a84b-bc0f85dce51e)
