### ISSUE TITLE
week2:通过EIDE工具链完成点灯任务，提交要求同week1

### ISSUE THREAD

**Issue by Liber1917** [Liber1917/Embedded_training_IEST#3]

**Comment by kinokono2** [comment]
![微信图片_20240601213046](https://github.com/Liber1917/Embedded_training_IEST/assets/171428103/e8cd24e7-413f-4681-9f57-f0ca273b8268)
![微信图片_20240601213111](https://github.com/Liber1917/Embedded_training_IEST/assets/171428103/e6b1e3cb-f875-469e-8391-8507bda9d6cb)
kinoko秽土转生版

**Comment by Liber1917** [comment]
> ![微信图片_20240601213046](https://private-user-images.githubusercontent.com/171428103/335804436-e8cd24e7-413f-4681-9f57-f0ca273b8268.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzg5NzcsIm5iZiI6MTcxNzMzODY3NywicGF0aCI6Ii8xNzE0MjgxMDMvMzM1ODA0NDM2LWU4Y2QyNGU3LTQxM2YtNDY4MS05ZjU3LWYwY2EyNzNiODI2OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNDMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGFlMTA0N2M3NzRmYjVmYTZiODBkZjUyOGEzOWE0YWRjNDU3OTAzYjliZTliNzM3MDViNDQxY2IwODBjZjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r5NofdDXVXTMRCq0di8xiQT5CbdTDm27nXPjha73Mls) ![微信图片_20240601213111](https://private-user-images.githubusercontent.com/171428103/335804439-e6b1e3cb-f875-469e-8391-8507bda9d6cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzg5NzcsIm5iZiI6MTcxNzMzODY3NywicGF0aCI6Ii8xNzE0MjgxMDMvMzM1ODA0NDM5LWU2YjFlM2NiLWY4NzUtNDY5ZS04MzkxLTg1MDdiZGE5ZDZjYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNDMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTM3YTgxZWEwODFjNWFjY2E5ZTA1ODNiZmNmODVlMzAyNThjN2U4NGY5NjBjZWFiMzY1NmExNDEyZWU4OTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AZ0OSH1JDmTJOrjYM7tjDoj5ukEWFMh-wsPLXChTqdg) kinoko秽土转生版

你的黑线怎么连的，看看配置(你的第二张截图含有大量无效信息)

**Comment by YouNeo1984** [comment]
![IMG_20240602_231706.jpg](https://github.com/Liber1917/Embedded_training_IEST/assets/164765259/3d035d0d-3704-4f2f-9f45-f33d9eae27a4)

![IMG_20240602_231831.jpg](https://github.com/Liber1917/Embedded_training_IEST/assets/164765259/af16489b-c88e-4fdb-a850-0c54e0e1edd2)

2024.6.2     自动化周子倜

**Comment by Liber1917** [comment]
> ![IMG_20240602_231706.jpg](https://private-user-images.githubusercontent.com/164765259/335877426-3d035d0d-3704-4f2f-9f45-f33d9eae27a4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDI0MjIsIm5iZiI6MTcxNzM0MjEyMiwicGF0aCI6Ii8xNjQ3NjUyNTkvMzM1ODc3NDI2LTNkMDM1ZDBkLTM3MDQtNGYyZi05ZjQ1LWYzM2Q5ZWFlMjdhNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNTI4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGRlZWM4YTczMjI0YTQ2MjNiMTM0YmQ0ODQzYTBlZTI5OGZhNjY5OWRiOTA2NzM4MmZlNjMzZjE2ZmI1MWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DlJ6LVaFYroGiQgZ9dXSPQFY3Naj3QyO2DylPyqcZlw)
> 
> ![IMG_20240602_231831.jpg](https://private-user-images.githubusercontent.com/164765259/335877427-af16489b-c88e-4fdb-a850-0c54e0e1edd2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDI0MjIsIm5iZiI6MTcxNzM0MjEyMiwicGF0aCI6Ii8xNjQ3NjUyNTkvMzM1ODc3NDI3LWFmMTY0ODliLWM4OGUtNGZkYi1hODUwLTBjNTRlMGUxZWRkMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNTI4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODMzZjY5NDFjOGIwNGE3ZDBlZjc4ZDFhOGM1NTgyZTMwZjYwMGNhYTFlYjhhOGMzZDNmZDYxZjVmM2E2NGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xkrFUehR_0g8tbA_Q2zIQSeY_b4nlhr_iG04xrqGw5c)
> 
> 2024.6.2 自动化周子倜

你编译成功的界面看一下

**Comment by YouNeo1984** [comment]
![IMG_20240603_011226.jpg](https://github.com/Liber1917/Embedded_training_IEST/assets/164765259/3c6b155c-c31a-45b9-a111-62ce2054556e)

https://github.com/Liber1917/Embedded_training_IEST/assets/164765259/a1e742cb-f951-4c7d-8786-d3e7e6d8798f

自动化周子倜

**Comment by kinokono2** [comment]
![2a16786f212530032bca5a729d22dd7](https://github.com/Liber1917/Embedded_training_IEST/assets/171428103/4bef715b-9931-4af9-a205-d306c4545bc7)
改用板载灯
